on:
  push:
    branches:
    - main

permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: pwd
    #  run: pwd
    #- name: ls
    #  run: ls
    - name: Install TeX
      run: sudo apt-get install texlive-full
    - name: Compile lesson1.tex
      run: ./compile.sh ./Notes/lesson1.tex
    - name: Compile lesson1-handout.tex
      run: ./compile.sh ./Notes/lesson1-handout.tex
    - name: Compile lesson2.tex
      run: ./compile.sh ./Notes/lesson2.tex
    - name: Compile lesson2-handout.tex
      run: ./compile.sh ./Notes/lesson2-handout.tex
      
