on:
  push:
    branches:
    - main

permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- name: pwd
    #  run: pwd
    #- name: ls
    #  run: ls
    - name: Setup
      run: sudo apt-get update && sudo apt-get install texlive-full
    - name: Change dir
      working-directory: ./Notes
      run: chmod +x ./compile.sh
    - name: Check dir
      working-directory: ./Notes
      run: pwd
    - name: Compile lesson1.tex
      working-directory: ./Notes
      run: ./compile.sh ./lesson1.tex
    - name: Compile lesson1-handout.tex
      working-directory: ./Notes
      run: ./compile.sh ./lesson1-handout.tex
    - name: Compile lesson2.tex
      working-directory: ./Notes
      run: ./compile.sh ./lesson2.tex
    - name: Compile lesson2-handout.tex
      working-directory: ./Notes
      run: ./compile.sh ./lesson2-handout.tex
      
